#!/usr/bin/env python3
# ===========================================================================
# scripts/make_synthetic.py  --  Write the ABM scenario parameter file
# ---------------------------------------------------------------------------
# Project 6.9 : Agent-Based Tissue / Immune Simulation
#
# This project's committed "data" is the SIMULATION SETUP (a one-line parameter
# file), not measured input -- the tissue state is generated by the solver. The
# actual cell positions are placed DETERMINISTICALLY inside the C++ loader from
# the `seed` in this file (a fixed LCG), so the whole run is reproducible from
# the sample alone and identical on every machine. This script only writes the
# parameter line.
#
# OUTPUT (data/README.md format), one line of 14 whitespace-separated fields:
#   gx gy dx steps dt D decay secretion radius k_rep chemotaxis seed n_tumor n_immune
#
# STABILITY: the explicit diffusion stencil needs D*dt/dx^2 <= 0.25 (2-D). The
# defaults below give 0.4*0.1/1 = 0.04, comfortably stable. The C++ loader
# re-checks this and refuses to run an unstable configuration.
#
# USAGE
#   python scripts/make_synthetic.py
#   python scripts/make_synthetic.py --gx 64 --gy 64 --n-tumor 400 --n-immune 300 --steps 800
# ===========================================================================
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "data" / "sample" / "tissue_params.txt"


def main():
    ap = argparse.ArgumentParser(description="Write the ABM tissue/immune scenario file.")
    ap.add_argument("--gx", type=int, default=32, help="substrate grid columns (x)")
    ap.add_argument("--gy", type=int, default=32, help="substrate grid rows (y)")
    ap.add_argument("--dx", type=float, default=1.0, help="grid spacing (domain units)")
    ap.add_argument("--steps", type=int, default=300, help="number of timesteps")
    ap.add_argument("--dt", type=float, default=0.1, help="timestep")
    ap.add_argument("--D", type=float, default=0.4, help="chemokine diffusion coefficient")
    ap.add_argument("--decay", type=float, default=0.02, help="chemokine first-order decay rate")
    ap.add_argument("--secretion", type=float, default=1.0, help="chemokine secreted per tumor cell per unit time")
    ap.add_argument("--radius", type=float, default=0.6, help="cell radius (repulsion within 2*radius)")
    ap.add_argument("--k-rep", type=float, default=1.0, help="soft-sphere repulsion stiffness")
    ap.add_argument("--chemotaxis", type=float, default=2.0, help="immune chemotactic speed per unit gradient")
    ap.add_argument("--seed", type=int, default=12345, help="RNG seed for the initial cell layout")
    ap.add_argument("--n-tumor", type=int, default=40, help="number of tumor cells (secretors)")
    ap.add_argument("--n-immune", type=int, default=30, help="number of immune cells (chemotactic)")
    ap.add_argument("--out", default=str(OUT))
    args = ap.parse_args()

    cfl = args.D * args.dt / (args.dx * args.dx)
    if cfl > 0.25:
        raise SystemExit(f"[make_synthetic] unstable: D*dt/dx^2 = {cfl:.3f} > 0.25; "
                         f"reduce --dt or --D.")

    fields = [args.gx, args.gy, args.dx, args.steps, args.dt, args.D, args.decay,
              args.secretion, args.radius, args.k_rep, args.chemotaxis,
              args.seed, args.n_tumor, args.n_immune]
    line = " ".join(str(f) for f in fields)
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text(line + "\n", encoding="utf-8")
    print(f"[make_synthetic] wrote {args.out}")
    print(f"  grid {args.gx}x{args.gy} dx={args.dx} steps={args.steps} dt={args.dt} "
          f"(D*dt/dx^2={cfl:.3f})")
    print(f"  cells: {args.n_tumor} tumor + {args.n_immune} immune  seed={args.seed}")


if __name__ == "__main__":
    main()
