#!/usr/bin/env python3
# ===========================================================================
# scripts/make_synthetic.py  --  Generate the synthetic CS-MRI sample dataset
# ---------------------------------------------------------------------------
# Project 4.3 : MRI Reconstruction with Compressed Sensing
#
# WHY THIS EXISTS
#   The real public datasets for this project (fastMRI, Calgary-Campinas, SKM-TEA)
#   require registration / a data-use agreement and CANNOT be redistributed here
#   (see data/README.md). So the committed demo runs on a SMALL, clearly-SYNTHETIC
#   phantom generated by this script. Nothing here is patient data.
#
# WHAT IT PRODUCES  (matches load_kspace() in src/reference_cpu.cpp)
#   A single n x n magnetic-resonance "image" that is SPARSE in image space (a few
#   bright blobs on a dark background -- like an MR angiogram, the classic CS use
#   case). We:
#     1. build the ground-truth image,
#     2. take its full 2D DFT -> full k-space,
#     3. apply a VARIABLE-DENSITY under-sampling mask (keep the low-frequency
#        center densely + a random subset of high frequencies -- the standard
#        CS-MRI sampling pattern), zero-filling the unsampled entries,
#     4. write "re im mask truth" per pixel so the reconstructor can (a) solve from
#        the under-sampled k-space and (b) score itself against the truth.
#
#   The mask is chosen with a FIXED random seed so the sample is reproducible and
#   the demo's expected_output.txt is stable.
#
#   Pure standard-library Python (no numpy) so it runs anywhere. n is small (32),
#   so the naive O(n^4) DFT here is instant; the C++/CUDA code uses a real FFT.
#
# USAGE
#   python scripts/make_synthetic.py                 # writes data/sample/kspace_sample.txt
#   python scripts/make_synthetic.py --n 64 --keep 0.34
# ===========================================================================
import argparse
import cmath
import math
import random
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent          # the project folder
OUT = ROOT / "data" / "sample" / "kspace_sample.txt"


def make_phantom(n):
    """Build a sparse n x n magnitude image: a few bright Gaussian blobs on 0.

    Sparse-in-image-space is exactly the regime where L1 compressed sensing shines
    (MR angiography). Returns a flat row-major list of floats, length n*n.
    """
    img = [0.0] * (n * n)
    # (center_row, center_col, amplitude, radius) for each blob, as fractions of n.
    blobs = [
        (0.30, 0.30, 1.00, 0.045),
        (0.55, 0.65, 0.80, 0.055),
        (0.70, 0.35, 0.60, 0.040),
        (0.40, 0.75, 0.90, 0.035),
    ]
    for (fr, fc, amp, frad) in blobs:
        cr, cc = fr * n, fc * n
        rad = frad * n
        for r in range(n):
            for c in range(n):
                d2 = (r - cr) ** 2 + (c - cc) ** 2
                img[r * n + c] += amp * math.exp(-d2 / (2.0 * rad * rad))
    return img


def dft2(img, n):
    """Naive 2D DFT (un-normalized forward) of a real image -> complex k-space.

    O(n^4); fine for the tiny synthetic n. Matches the convention of fft2_cpu /
    cuFFT CUFFT_FORWARD:  X[k1,k2] = sum_{r,c} img[r,c] exp(-2pi i (k1 r + k2 c)/n).
    Returns a flat row-major list of complex numbers, length n*n.
    """
    ks = [0j] * (n * n)
    two_pi = 2.0 * math.pi
    for k1 in range(n):
        for k2 in range(n):
            acc = 0j
            for r in range(n):
                # Precompute the row phase factor once per (k1, r).
                ph_r = -two_pi * k1 * r / n
                base = cmath.exp(1j * ph_r)
                for c in range(n):
                    ph = base * cmath.exp(-1j * two_pi * k2 * c / n)
                    acc += img[r * n + c] * ph
            ks[k1 * n + k2] = acc
    return ks


def variable_density_mask(n, keep_frac, center_frac, seed):
    """A variable-density Cartesian under-sampling mask (row-major, length n*n).

    Keeps ALL of a low-frequency square in the k-space center (frequencies wrap so
    the center is the [0..cw] and [n-cw..n-1] indices) -- the low frequencies carry
    most MR energy and must be sampled -- plus a random subset of the rest until the
    total sampled fraction ~= keep_frac. Fixed seed -> reproducible sample.
    """
    rng = random.Random(seed)
    mask = [0] * (n * n)
    cw = max(1, int(round(center_frac * n / 2)))   # half-width of the dense center
    def is_center(k):
        return k < cw or k >= n - cw
    # Dense center block.
    for k1 in range(n):
        for k2 in range(n):
            if is_center(k1) and is_center(k2):
                mask[k1 * n + k2] = 1
    # Randomly fill the periphery up to the target count.
    target = int(round(keep_frac * n * n))
    periphery = [i for i in range(n * n) if mask[i] == 0]
    rng.shuffle(periphery)
    have = sum(mask)
    for i in periphery:
        if have >= target:
            break
        mask[i] = 1
        have += 1
    return mask


def main():
    ap = argparse.ArgumentParser(description="Generate the synthetic CS-MRI sample.")
    ap.add_argument("--n", type=int, default=32, help="image side (power of two)")
    ap.add_argument("--keep", type=float, default=0.34, help="fraction of k-space sampled")
    ap.add_argument("--center", type=float, default=0.28, help="fraction kept fully dense at center")
    ap.add_argument("--lam", type=float, default=0.010, help="FISTA L1 weight lambda")
    ap.add_argument("--iters", type=int, default=60, help="FISTA iterations")
    ap.add_argument("--seed", type=int, default=1234, help="RNG seed (reproducible mask)")
    ap.add_argument("--out", default=str(OUT), help="output path")
    args = ap.parse_args()

    n = args.n
    assert n > 0 and (n & (n - 1)) == 0, "n must be a power of two"

    truth = make_phantom(n)                              # ground-truth sparse image
    kfull = dft2(truth, n)                               # full k-space
    mask = variable_density_mask(n, args.keep, args.center, args.seed)

    # Zero-fill the unsampled k-space entries (that is what the scanner "gives" us).
    lines = [f"{n} {args.lam:g} {args.iters} 1"]         # header: n lambda iters has_truth
    for i in range(n * n):
        if mask[i]:
            z = kfull[i]
            re, im = z.real, z.imag
        else:
            re, im = 0.0, 0.0                            # unsampled -> zero-filled
        lines.append(f"{re:.7g} {im:.7g} {mask[i]} {truth[i]:.7g}")

    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text("\n".join(lines) + "\n", encoding="utf-8")
    n_samp = sum(mask)
    print(f"[make_synthetic] wrote {args.out}")
    print(f"[make_synthetic] n={n}, sampled {n_samp}/{n*n} "
          f"({100.0*n_samp/(n*n):.1f}%), lambda={args.lam}, iters={args.iters}; SYNTHETIC")


if __name__ == "__main__":
    main()
