# ===========================================================================
# scripts/download_data.ps1  --  Fetch the FULL dataset (Windows / PowerShell)
# ---------------------------------------------------------------------------
# Project 1.6 : Enhanced Sampling -- Metadynamics & Replica Exchange
#
# CONTRACT (CLAUDE.md §8): idempotent, documented, prints source URLs, and NEVER
# bypasses credentials/registration. This project's demo input is FULLY SYNTHETIC
# (a 1-D model configuration generated by make_synthetic.py), so there is no
# required download. This script instead points to REAL enhanced-sampling study
# material for learners who want to go further, with registration instructions
# only -- it never logs in or scrapes on your behalf.
#
# Usage:  ./scripts/download_data.ps1
# ===========================================================================
$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path -Parent $PSScriptRoot
$DataDir = Join-Path $ProjectRoot "data"

Write-Host "[download_data] Project 1.6 -- Enhanced Sampling -- Metadynamics & Replica Exchange"
Write-Host "[download_data] Target data dir: $DataDir"
Write-Host ""
Write-Host "This project needs NO download: the demo runs on a synthetic 1-D model."
Write-Host "  Regenerate / rescale the committed sample with:"
Write-Host "    python scripts/make_synthetic.py                 # default 64-walker run"
Write-Host "    python scripts/make_synthetic.py --n-walkers 256 --steps 40000"
Write-Host ""
Write-Host "To study REAL enhanced sampling, explore these (free, but follow each"
Write-Host "site's terms; some need a free account -- this script does NOT log in):"
Write-Host "  * PLUMED-NEST   https://www.plumed-nest.org   (published MetaD/REST2 inputs;"
Write-Host "                  start with the alanine-dipeptide well-tempered MetaD example)"
Write-Host "  * GPCRmd        https://gpcrmd.org            (GPCR MD trajectories; free account)"
Write-Host "  * D.E.Shaw MD   via RCSB / by request         (long-timescale trajectories)"
Write-Host ""
Write-Host "  When wiring a real dataset later, keep it idempotent:"
Write-Host "    1) skip the download if the file already exists with the right checksum"
Write-Host "    2) print source URL + expected size + SHA256"
Write-Host "    3) for credentialed sets, print registration instructions ONLY"
