#!/usr/bin/env bash
# ===========================================================================
# scripts/download_data.sh  --  Fetch the FULL dataset (Linux / macOS)
# ---------------------------------------------------------------------------
# Project 1.6 : Enhanced Sampling -- Metadynamics & Replica Exchange
#
# CONTRACT (CLAUDE.md §8): idempotent, documented, prints source URLs, and NEVER
# bypasses credentials/registration. This project's demo input is FULLY SYNTHETIC
# (a 1-D model configuration generated by make_synthetic.py), so there is no
# required download. This script instead points to REAL enhanced-sampling study
# material for learners who want to go further, with registration instructions
# only -- it never logs in or scrapes on your behalf.
#
# Usage:  ./scripts/download_data.sh
# ===========================================================================
set -euo pipefail
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DATA_DIR="$PROJECT_ROOT/data"

echo "[download_data] Project 1.6 -- Enhanced Sampling -- Metadynamics & Replica Exchange"
echo "[download_data] Target data dir: $DATA_DIR"
echo
echo "This project needs NO download: the demo runs on a synthetic 1-D model."
echo "  Regenerate / rescale the committed sample with:"
echo "    python scripts/make_synthetic.py                 # default 64-walker run"
echo "    python scripts/make_synthetic.py --n-walkers 256 --steps 40000"
echo
echo "To study REAL enhanced sampling, explore these (free, but follow each"
echo "site's terms; some need a free account -- this script does NOT log in):"
echo "  * PLUMED-NEST   https://www.plumed-nest.org   (published MetaD/REST2 inputs;"
echo "                  start with the alanine-dipeptide well-tempered MetaD example)"
echo "  * GPCRmd        https://gpcrmd.org            (GPCR MD trajectories; free account)"
echo "  * D.E.Shaw MD   via RCSB / by request         (long-timescale trajectories)"
echo
echo "  When wiring a real dataset later, keep it idempotent:"
echo "    1) skip the download if the file already exists with the right checksum"
echo "    2) print source URL + expected size + SHA256"
echo "    3) for credentialed sets, print registration instructions ONLY"
