#!/usr/bin/env bash
# ===========================================================================
# scripts/download_data.sh  --  Fetch the FULL dataset (Linux / macOS)
# ---------------------------------------------------------------------------
# Project 1.25 : Gaussian-Accelerated MD (GaMD)   (reduced-scope teaching version)
#
# CONTRACT (CLAUDE.md §8): idempotent, documented, prints the source URLs, and
# NEVER bypasses credentials/registration. This project's demo needs NO download
# at all -- it runs on a 1-D model system whose config is committed in
# data/sample/ and regenerated by scripts/make_synthetic.py. This script only
# points you to the REAL all-atom GaMD resources you would use for a full study.
#
# Usage:  ./scripts/download_data.sh
# ===========================================================================
set -euo pipefail
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DATA_DIR="$PROJECT_ROOT/data"

echo "[download_data] Project 1.25 -- Gaussian-Accelerated MD (GaMD)"
echo "[download_data] Target data dir: $DATA_DIR"
echo
echo "This project is a REDUCED-SCOPE teaching version on a 1-D model potential."
echo "No dataset download is required: the committed data/sample/gamd_config.txt"
echo "is enough to build and run the demo. To (re)generate it or a bigger run:"
echo "    python scripts/make_synthetic.py                 # default sample"
echo "    python scripts/make_synthetic.py --n-walkers 4096 --steps 20000"
echo
echo "For a REAL all-atom GaMD study, see (no auto-download; visit + follow each):"
echo "  * AMBER GaMD tutorials : https://www.med.unc.edu/pharm/miaolab/resources/gamd/"
echo "  * GPCRmd MD systems    : https://gpcrmd.org"
echo "  * D. E. Shaw Research benchmark trajectories (long-timescale ground truth)"
echo "  * RCSB PDB structures  : https://www.rcsb.org"
echo
echo "Some of those require registration/accounts; this script does NOT bypass"
echo "them -- it only prints the links (CLAUDE.md section 8)."
