# ===========================================================================
# scripts/download_data.ps1  --  Fetch the FULL dataset (Windows / PowerShell)
# ---------------------------------------------------------------------------
# Project 1.25 : Gaussian-Accelerated MD (GaMD)   (reduced-scope teaching version)
#
# CONTRACT (CLAUDE.md §8): idempotent, documented, prints the source URLs, and
# NEVER bypasses credentials/registration. This project's demo needs NO download
# at all -- it runs on a 1-D model system whose config is committed in
# data/sample/ and regenerated by scripts/make_synthetic.py. This script only
# points you to the REAL all-atom GaMD resources you would use for a full study.
#
# Usage:  ./scripts/download_data.ps1
# ===========================================================================
$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path -Parent $PSScriptRoot
$DataDir = Join-Path $ProjectRoot "data"

Write-Host "[download_data] Project 1.25 -- Gaussian-Accelerated MD (GaMD)"
Write-Host "[download_data] Target data dir: $DataDir"
Write-Host ""
Write-Host "This project is a REDUCED-SCOPE teaching version on a 1-D model potential."
Write-Host "No dataset download is required: the committed data/sample/gamd_config.txt"
Write-Host "is enough to build and run the demo. To (re)generate it or a bigger run:"
Write-Host "    python scripts/make_synthetic.py                 # default sample"
Write-Host "    python scripts/make_synthetic.py --n-walkers 4096 --steps 20000"
Write-Host ""
Write-Host "For a REAL all-atom GaMD study, see (no auto-download; visit + follow each):"
Write-Host "  * AMBER GaMD tutorials : https://www.med.unc.edu/pharm/miaolab/resources/gamd/"
Write-Host "  * GPCRmd MD systems    : https://gpcrmd.org"
Write-Host "  * D. E. Shaw Research benchmark trajectories (long-timescale ground truth)"
Write-Host "  * RCSB PDB structures  : https://www.rcsb.org"
Write-Host ""
Write-Host "Some of those require registration/accounts; this script does NOT bypass"
Write-Host "them -- it only prints the links (CLAUDE.md section 8)."
