// ===========================================================================
// src/bergman.h  --  Shared (host + device) glucose-insulin model + closed-loop
//                    RK4 integrator for one virtual patient
// ---------------------------------------------------------------------------
// Project 6.23 : Glucose-Insulin Dynamics & Artificial Pancreas
//
// WHAT THIS PROJECT COMPUTES
//   An ENSEMBLE of closed-loop artificial-pancreas simulations: the SAME
//   glucose-insulin ODE (Bergman's minimal model) integrated for a whole COHORT
//   of virtual Type-1-diabetes patients, each with different physiology, while a
//   PID controller doses insulin in real time to keep blood glucose in range.
//   Each patient is an INDEPENDENT ODE solve driven by its own controller, so we
//   give each virtual patient its own GPU thread -- the natural mapping for the
//   in-silico trials the UVA/Padova simulator was built for.
//
// THE MODEL (Bergman "minimal model", the teaching workhorse of glucose kinetics)
//   Three ODE state variables (all continuous, all per-patient):
//     G(t)  = plasma glucose concentration       [mg/dL]
//     X(t)  = "remote" insulin action in tissue   [1/min]   (insulin in the
//             interstitium that actually drives glucose uptake -- lags plasma
//             insulin, which is why X is a separate compartment)
//     I(t)  = plasma insulin concentration        [micro-U/mL]
//
//   Governing equations (units chosen so the numbers look clinical):
//     dG/dt = -(p1 + X) * G + p1 * Gb + Ra(t) / VG
//     dX/dt = -p2 * X + p3 * (I - Ib)
//     dI/dt = -n * (I - Ib) + u(t) / VI
//   where
//     p1     = glucose effectiveness (SG): glucose self-clears at basal insulin
//     p2,p3  = insulin-action kinetics; SI = p3/p2 is the INSULIN SENSITIVITY
//              (the single most patient-variable parameter -- low SI = insulin
//              resistant, needs more insulin)
//     Gb,Ib  = basal (fasting) glucose and insulin set-points
//     n      = plasma-insulin clearance rate
//     VG,VI  = glucose / insulin distribution volumes (dL/kg, mL/kg scale)
//     Ra(t)  = rate of glucose appearance from a meal (gut absorption), below
//     u(t)   = exogenous insulin infusion rate the CONTROLLER chooses, below
//
// THE MEAL (glucose disturbance Ra(t))
//   A carbohydrate meal is absorbed with a smooth rise-and-fall. We use the
//   classic two-exponential "gastric emptying" impulse response:
//     Ra(t) = D * Ag * k^2 * (t - t_meal) * exp(-k * (t - t_meal))   for t >= t_meal
//   D  = carbs in the meal [mg], Ag = bioavailability, k = 1/absorption-time.
//   This peaks at t_meal + 1/k then decays -- a single "hump" of glucose input.
//
// THE CONTROLLER (the "artificial pancreas": closed-loop insulin dosing)
//   A discrete PID controller runs every control_dt minutes. It reads glucose
//   (here noiselessly; a real CGM adds noise -> Kalman filter, THEORY & exercises)
//   and sets the insulin infusion rate:
//     e      = G - G_target                         (error, mg/dL)
//     P term = Kp * e
//     I term = Ki * integral(e dt)                  (accumulated error)
//     D term = Kd * dG/dt                            (glucose rate of change)
//     u = clamp(u_basal + Kp*e + Ki*I_acc + Kd*dG, 0, u_max)
//   Insulin can only be added (u >= 0: you cannot suck insulin back out), so the
//   command is clamped at zero and at a pump maximum.
//
//   The controller state (integral accumulator, last glucose) is carried in the
//   PatientState alongside G,X,I. The ODE RHS AND the RK4 step live here as
//   BERG_HD (=__host__ __device__ under nvcc, nothing on the host compiler) so the
//   CPU reference and the GPU kernel integrate the SAME closed loop -> their
//   results match to round-off.
//
//   NOT FOR CLINICAL USE. Illustrative parameters; see README/THEORY.
// ===========================================================================
#pragma once

#include <cmath>   // std::exp on the host side (device uses the CUDA math exp)

#ifdef __CUDACC__
#define BERG_HD __host__ __device__   // compiled by nvcc: real CUDA decorators
#else
#define BERG_HD                        // host compiler: the decorators don't exist
#endif

// Forward declaration: meal_appearance() calls exp_hd() before its definition
// (both are inline, so a prior declaration is all the compiler needs).
BERG_HD inline double exp_hd(double x);

// ---------------------------------------------------------------------------
// PatientParams: the per-patient physiology + fixed pump/meal settings.
//   Everything a single virtual patient needs to be simulated. The cohort is
//   generated by sweeping the two most clinically-variable parameters --
//   insulin sensitivity (via p3) and glucose effectiveness (p1) -- across a grid
//   (see reference_cpu.h : patient_params()).
// ---------------------------------------------------------------------------
struct PatientParams {
    // --- Bergman minimal-model constants (units in bergman.h header) ---
    double p1;      // glucose effectiveness SG            [1/min]
    double p2;      // remote-insulin decay rate           [1/min]
    double p3;      // insulin-action gain                 [1/min per (uU/mL)]
    double n;       // plasma insulin clearance            [1/min]
    double Gb;      // basal glucose set-point             [mg/dL]
    double Ib;      // basal insulin set-point             [uU/mL]
    double VG;      // glucose distribution volume          [dL/kg]  (scales Ra)
    double VI;      // insulin distribution volume          [mL/kg]  (scales u)

    // --- Meal (glucose disturbance) ---
    double meal_D;      // meal carbohydrate load          [mg glucose]
    double meal_Ag;     // meal bioavailability (0..1)     [-]
    double meal_k;      // gut-absorption rate             [1/min]  (peak at t_meal+1/k)
    double meal_t;      // meal start time                 [min]

    // --- Closed-loop PID controller + pump ---
    double G_target;    // glucose set-point               [mg/dL]  (e.g. 110)
    double Kp, Ki, Kd;  // PID gains
    double u_basal;     // basal insulin infusion          [uU/min-equivalent]
    double u_max;       // pump maximum infusion            [same units]
    double control_dt;  // controller update period        [min]

    // --- Integration ---
    double G0;          // initial glucose                 [mg/dL]
    double dt;          // RK4 timestep                    [min]
    int    steps;       // number of RK4 steps (run = steps*dt minutes)
};

// ---------------------------------------------------------------------------
// PatientState: the evolving state of one simulation.
//   The three physiological compartments PLUS the controller's memory. Keeping
//   the controller state here (not in globals) is what makes each thread a fully
//   independent closed loop.
// ---------------------------------------------------------------------------
struct PatientState {
    double G;         // plasma glucose      [mg/dL]
    double X;         // remote insulin action [1/min]
    double I;         // plasma insulin      [uU/mL]
    double u;         // current insulin infusion command (held between updates)
    double err_acc;   // PID integral accumulator (integral of error*dt)
    double G_prev;    // glucose at the previous control tick (for the D term)
};

// ---------------------------------------------------------------------------
// meal_appearance: Ra(t), the rate of glucose entering plasma from the gut.
//   Two-exponential gastric-emptying impulse response (see header). Zero before
//   the meal; a single smooth hump afterwards. Returned in [mg/min].
// ---------------------------------------------------------------------------
BERG_HD inline double meal_appearance(const PatientParams& p, double t) {
    if (t < p.meal_t) return 0.0;                 // meal hasn't started yet
    const double tau = t - p.meal_t;              // minutes since the meal
    // D*Ag*k^2 * tau * exp(-k*tau): area under the curve = D*Ag (total absorbed).
    return p.meal_D * p.meal_Ag * p.meal_k * p.meal_k * tau *
           exp_hd(-p.meal_k * tau);
}

// ---------------------------------------------------------------------------
// bergman_deriv: the minimal-model right-hand side.
//   Given the current state and the *currently commanded* insulin infusion `u`
//   and meal input Ra, write the three time-derivatives (dG, dX, dI). The
//   controller is held constant across an RK4 step (zero-order hold), exactly as
//   a real digital controller behaves between updates.
// ---------------------------------------------------------------------------
BERG_HD inline void bergman_deriv(const PatientParams& p,
                                  double G, double X, double I,
                                  double u, double Ra,
                                  double& dG, double& dX, double& dI) {
    // Glucose: removed by (baseline effectiveness p1 + insulin action X), pulled
    // toward basal by p1*Gb, and raised by the meal (Ra spread over volume VG).
    dG = -(p.p1 + X) * G + p.p1 * p.Gb + Ra / p.VG;
    // Remote insulin action X relaxes toward p3/p2 * (I - Ib): the driver of
    // insulin-dependent glucose uptake. SI = p3/p2 is the insulin sensitivity.
    dX = -p.p2 * X + p.p3 * (I - p.Ib);
    // Plasma insulin clears at rate n toward basal Ib, raised by infusion u/VI.
    dI = -p.n * (I - p.Ib) + u / p.VI;
}

// ---------------------------------------------------------------------------
// rk4_step: one classical 4th-order Runge-Kutta step of the 3-state ODE.
//   The controller command `u` and the meal term are sampled ONCE per step
//   (zero-order hold) -- a digital controller does not change mid-step. RK4 is
//   O(dt^4) accurate and stable for these smooth, mildly-stiff dynamics.
//   Advances G, X, I in place.
// ---------------------------------------------------------------------------
BERG_HD inline void rk4_step(const PatientParams& p,
                             double& G, double& X, double& I,
                             double u, double t) {
    const double dt = p.dt;
    const double Ra = meal_appearance(p, t + 0.5 * dt);   // midpoint meal rate
    double k1G, k1X, k1I, k2G, k2X, k2I, k3G, k3X, k3I, k4G, k4X, k4I;

    bergman_deriv(p, G,               X,               I,               u, Ra, k1G, k1X, k1I);
    bergman_deriv(p, G + 0.5*dt*k1G,  X + 0.5*dt*k1X,  I + 0.5*dt*k1I,  u, Ra, k2G, k2X, k2I);
    bergman_deriv(p, G + 0.5*dt*k2G,  X + 0.5*dt*k2X,  I + 0.5*dt*k2I,  u, Ra, k3G, k3X, k3I);
    bergman_deriv(p, G + dt*k3G,      X + dt*k3X,      I + dt*k3I,      u, Ra, k4G, k4X, k4I);

    G += (dt / 6.0) * (k1G + 2.0*k2G + 2.0*k3G + k4G);
    X += (dt / 6.0) * (k1X + 2.0*k2X + 2.0*k3X + k4X);
    I += (dt / 6.0) * (k1I + 2.0*k2I + 2.0*k3I + k4I);
}

// ---------------------------------------------------------------------------
// pid_update: recompute the insulin infusion command from the current glucose.
//   Runs at the control tick. `dt_ctrl` is the time since the last update (used
//   for the integral and derivative terms). Updates the controller memory in the
//   PatientState and returns the clamped infusion rate.
//
//   Sign convention: high glucose (e>0) -> MORE insulin (Kp>0). The derivative
//   term reacts to glucose *rising* to pre-empt overshoot. Anti-windup: we clamp
//   the command and only integrate while not saturated (a simple, standard trick).
// ---------------------------------------------------------------------------
BERG_HD inline double pid_update(const PatientParams& p, PatientState& s, double dt_ctrl) {
    const double e  = s.G - p.G_target;                   // glucose error [mg/dL]
    const double dG = (dt_ctrl > 0.0) ? (s.G - s.G_prev) / dt_ctrl : 0.0;  // rate

    // Tentative integral update (added below only if it does not deepen saturation).
    const double err_acc_try = s.err_acc + e * dt_ctrl;

    double u = p.u_basal + p.Kp * e + p.Ki * err_acc_try + p.Kd * dG;

    // Clamp to the physically realizable pump range [0, u_max].
    bool saturated_hi = false, saturated_lo = false;
    if (u > p.u_max) { u = p.u_max; saturated_hi = true; }
    if (u < 0.0)     { u = 0.0;     saturated_lo = true; }

    // Anti-windup: only commit the integral if we are not pinned against a limit
    // in the direction that would wind it further (prevents the I-term ballooning
    // while the pump is maxed out or off).
    const bool winding_up   = saturated_hi && (e > 0.0);
    const bool winding_down = saturated_lo && (e < 0.0);
    if (!winding_up && !winding_down) s.err_acc = err_acc_try;

    s.G_prev = s.G;    // remember glucose for the next derivative estimate
    s.u = u;
    return u;
}

// ---------------------------------------------------------------------------
// PatientResult: the per-patient clinical summary the trial cares about.
//   These are the standard closed-loop glucose-control metrics. Time-in-range
//   (TIR, 70-180 mg/dL) is the primary outcome in modern artificial-pancreas
//   trials; hypoglycemia (<70) is the dangerous failure mode.
// ---------------------------------------------------------------------------
struct PatientResult {
    double min_G;         // minimum glucose over the run     [mg/dL]
    double max_G;         // maximum glucose over the run     [mg/dL]
    double mean_G;        // time-averaged glucose            [mg/dL]
    double tir_frac;      // fraction of time in [70,180]     [0..1]
    double hypo_frac;     // fraction of time < 70            [0..1]
    double hyper_frac;    // fraction of time > 180           [0..1]
    double insulin_total; // total insulin delivered (integral of u)
};

// ---------------------------------------------------------------------------
// simulate_patient: run ONE virtual patient's closed-loop simulation to the end
//   and return its summary metrics. This is the single function shared verbatim
//   by the CPU reference (looped over the cohort) and the GPU kernel (one thread
//   per patient) -- guaranteeing identical math on both sides.
//
//   The loop:
//     * every step advances the ODE by dt (RK4, zero-order-hold controller);
//     * at each control tick (every control_dt) the PID recomputes u;
//     * glucose is accumulated into the clinical metrics each step.
//   Complexity: O(steps) per patient; the ensemble is O(cohort * steps) total.
// ---------------------------------------------------------------------------
BERG_HD inline PatientResult simulate_patient(const PatientParams& p) {
    PatientState s;
    s.G = p.G0;
    s.X = 0.0;                       // start at rest: no remote insulin action
    s.I = p.Ib;                      // plasma insulin at basal
    s.err_acc = 0.0;
    s.G_prev = p.G0;
    s.u = p.u_basal;

    // How many RK4 steps per controller tick (control_dt is a multiple of dt).
    int steps_per_ctrl = (int)(p.control_dt / p.dt + 0.5);
    if (steps_per_ctrl < 1) steps_per_ctrl = 1;

    // Metric accumulators. We tally per-step (trapezoid-free rectangle rule is
    // fine at this dt) so the fractions are time-weighted.
    double min_G = s.G, max_G = s.G, sum_G = 0.0;
    long   in_range = 0, hypo = 0, hyper = 0;   // step counts
    double insulin_total = 0.0;

    double u = p.u_basal;   // held command (zero-order hold between ticks)
    for (int k = 0; k < p.steps; ++k) {
        const double t = k * p.dt;

        // Controller tick? Recompute the infusion command from current glucose.
        // dt_ctrl is the fixed control period; at k==0 s.G_prev==G0 so the
        // derivative term is 0 (no spurious kick on the first tick).
        if (k % steps_per_ctrl == 0) {
            u = pid_update(p, s, p.control_dt);
        }

        // Advance the physiology one RK4 step under the held command u.
        rk4_step(p, s.G, s.X, s.I, u, t);

        // Tally clinical metrics on the NEW glucose.
        if (s.G < min_G) min_G = s.G;
        if (s.G > max_G) max_G = s.G;
        sum_G += s.G;
        if (s.G < 70.0)       ++hypo;
        else if (s.G > 180.0) ++hyper;
        else                  ++in_range;
        insulin_total += u * p.dt;   // integral of infusion = total insulin
    }

    PatientResult r;
    r.min_G  = min_G;
    r.max_G  = max_G;
    r.mean_G = sum_G / p.steps;
    r.tir_frac   = (double)in_range / p.steps;
    r.hypo_frac  = (double)hypo     / p.steps;
    r.hyper_frac = (double)hyper    / p.steps;
    r.insulin_total = insulin_total;
    return r;
}

// --- exp_hd definition (after first use is fine for inline functions) --------
// On the device nvcc maps ::exp(double) to the hardware double-precision exp;
// on the host it is std::exp. We wrap it so meal_appearance() reads cleanly and
// so the CPU and GPU call the *same* math (double exp) for bit-parity.
BERG_HD inline double exp_hd(double x) {
#ifdef __CUDA_ARCH__
    return exp(x);        // device: CUDA math library double exp
#else
    return std::exp(x);   // host: standard library
#endif
}
