// ===========================================================================
// src/reference_cpu.h  --  Params I/O, field seeding, and the CPU reference
// ---------------------------------------------------------------------------
// Project 6.24 : Reaction-Diffusion Morphogenesis (Turing Patterns)
//
// Pure C++ (no CUDA), so it is safe to #include from both reference_cpu.cpp
// (host compiler) and kernels.cu / main.cu (nvcc). The per-cell PHYSICS lives
// in turing.h; this header only declares the surrounding scaffolding:
//   * load_params : read the one-line parameter file (data/README.md format).
//   * init_fields : build the near-uniform, deterministically-perturbed seed.
//   * simulate_cpu: the trusted serial baseline the GPU stencil is checked
//     against (it runs the EXACT same tu_update() as the kernel).
//
// The CPU and GPU seed from init_fields() (identical numbers) and run the same
// tu_update(), so their final fields must agree within the tolerance discussed
// in THEORY.md §"How we verify correctness."
// ===========================================================================
#pragma once

#include <string>
#include <vector>

#include "turing.h"   // TuringParams, tu_update, tu_laplacian, tu_baseline_activator

// Load TuringParams from the whitespace-separated one-line format:
//   "nx ny Da Dh rho mu_a mu_h rho_a dt steps noise_seed"
// Throws std::runtime_error on a missing file or malformed / invalid values.
TuringParams load_params(const std::string& path);

// Seed the two fields for a run. Both are sized nx*ny (row-major).
//   activator a  <- baseline + a tiny DETERMINISTIC per-cell perturbation
//   inhibitor h  <- the matching baseline (so the state starts near-uniform)
// The perturbation is generated by a small integer hash of (x, y, noise_seed),
// NOT by rand(), so the initial condition is bit-identical on every machine and
// on both host and device paths -- essential for a reproducible demo (PATTERNS
// §3) and for an exact CPU-vs-GPU comparison.
void init_fields(const TuringParams& P, std::vector<double>& a, std::vector<double>& h);

// CPU reference: advance the fields `steps` timesteps IN PLACE, using a private
// double buffer and swapping each step (ping-pong), exactly like the GPU loop.
// This is the ground truth for verification.
void simulate_cpu(const TuringParams& P, std::vector<double>& a, std::vector<double>& h);

// ---------------------------------------------------------------------------
// tu_perturbation  --  the deterministic initial noise at cell (x,y).
//
// Declared here (defined in reference_cpu.cpp) and used ONLY at t=0 to break the
// perfect symmetry of the uniform state so a pattern can nucleate. It returns a
// tiny value in about [-amp, +amp]. Being a pure function of (x,y,seed) makes
// the seed reproducible without any RNG state. Shared so main.cu could reuse it.
// ---------------------------------------------------------------------------
double tu_perturbation(int x, int y, int seed, double amp);
