#!/usr/bin/env bash
# ===========================================================================
# scripts/download_data.sh  --  Fetch the FULL dataset (Linux / macOS)
# ---------------------------------------------------------------------------
# Project 6.16 : Cardiac Mechanics & Electromechanical Coupling
#
# CONTRACT (CLAUDE.md §8): idempotent, documented, prints source URL + expected
# size, and NEVER bypasses credentials/registration. This project's demo runs
# entirely on a SYNTHETIC, self-generated config (there is no raw dataset to
# fetch), so this script only prints guidance + the catalog's real-data
# pointers and defers to scripts/make_synthetic.py.
#
# Usage:  ./scripts/download_data.sh
# ===========================================================================
set -euo pipefail
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DATA_DIR="$PROJECT_ROOT/data"

echo "[download_data] Project 6.16 -- Cardiac Mechanics & Electromechanical Coupling"
echo "[download_data] Target data dir: $DATA_DIR"
echo
echo "This project needs NO downloaded dataset: the demo runs on a synthetic"
echo "heart-ensemble CONFIG generated by scripts/make_synthetic.py. Regenerate or"
echo "enlarge it with, e.g.:"
echo "    python scripts/make_synthetic.py --nT 32 --nR 32   # 1024 virtual hearts"
echo
echo "REAL cardiac imaging / mechanics datasets to study (accounts/registration"
echo "may be required -- follow each site's terms; this script does NOT bypass them):"
echo "  * UK Biobank CMR + strain imaging   https://www.ukbiobank.ac.uk"
echo "  * Zenodo cardiac-mechanics emulation https://zenodo.org/records/7075055"
echo "  * ACDC segmentation challenge        https://www.creatis.insa-lyon.fr/Challenge/acdc/"
echo "  * MICCAI STACOM cardiac mechanics    (verify current URL on grand-challenge.org)"
echo
echo "When wiring a real dataset, follow this idempotent pattern:"
echo "  1) skip download if the file already exists with the right checksum"
echo "  2) print source URL + expected size + SHA256"
echo "  3) for credentialed sets, print registration instructions ONLY"
