# ===========================================================================
# scripts/download_data.ps1  --  Fetch the FULL dataset (Windows / PowerShell)
# ---------------------------------------------------------------------------
# Project 6.16 : Cardiac Mechanics & Electromechanical Coupling
#
# CONTRACT (CLAUDE.md §8): idempotent, documented, prints the source URL +
# expected size, and NEVER bypasses credentials/registration. This project's
# demo runs entirely on a SYNTHETIC, self-generated config (there is no raw
# dataset to fetch), so this script only prints guidance + the catalog's
# real-data pointers and defers to scripts/make_synthetic.py.
#
# Usage:  ./scripts/download_data.ps1
# ===========================================================================
$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path -Parent $PSScriptRoot
$DataDir = Join-Path $ProjectRoot "data"

Write-Host "[download_data] Project 6.16 -- Cardiac Mechanics & Electromechanical Coupling"
Write-Host "[download_data] Target data dir: $DataDir"
Write-Host ""
Write-Host "This project needs NO downloaded dataset: the demo runs on a synthetic"
Write-Host "heart-ensemble CONFIG generated by scripts/make_synthetic.py. Regenerate or"
Write-Host "enlarge it with, e.g.:"
Write-Host "    python scripts/make_synthetic.py --nT 32 --nR 32   # 1024 virtual hearts"
Write-Host ""
Write-Host "REAL cardiac imaging / mechanics datasets to study (accounts/registration"
Write-Host "may be required -- follow each site's terms; this script does NOT bypass them):"
Write-Host "  * UK Biobank CMR + strain imaging   https://www.ukbiobank.ac.uk"
Write-Host "  * Zenodo cardiac-mechanics emulation https://zenodo.org/records/7075055"
Write-Host "  * ACDC segmentation challenge        https://www.creatis.insa-lyon.fr/Challenge/acdc/"
Write-Host "  * MICCAI STACOM cardiac mechanics    (verify current URL on grand-challenge.org)"
Write-Host ""
Write-Host "When wiring a real dataset, follow this idempotent pattern:"
Write-Host "  1) skip download if the file already exists with the right checksum"
Write-Host "  2) print source URL + expected size + SHA256"
Write-Host "  3) for credentialed sets, print registration instructions ONLY"
