#!/usr/bin/env bash
# ===========================================================================
# scripts/download_data.sh  --  Fetch a FULL dataset (Linux / macOS)
# ---------------------------------------------------------------------------
# Project 6.11 : Stochastic (Gillespie) Biochemical Simulation
#
# CONTRACT (CLAUDE.md §8): idempotent, documented, prints source URLs, and NEVER
# bypasses credentials/registration. This project's demo needs NO download -- its
# input is a tiny synthetic model spec generated by make_synthetic.py. This
# script only points you at real curated models for further study.
#
# Usage:  ./scripts/download_data.sh
# ===========================================================================
set -euo pipefail
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DATA_DIR="$PROJECT_ROOT/data"

echo "[download_data] Project 6.11 -- Stochastic (Gillespie) Biochemical Simulation"
echo "[download_data] Target data dir: $DATA_DIR"
echo
echo "This project does NOT require a downloaded dataset:"
echo "  the committed data/sample/gene_network.txt (a synthetic model spec) is"
echo "  sufficient to build, run, and verify the demo offline."
echo
echo "For a larger SYNTHETIC ensemble, run:"
echo "    python scripts/make_synthetic.py --n-traj 4096"
echo
echo "To study REAL stochastic reaction networks (adapt build_gene_network()"
echo "in src/reference_cpu.cpp to their stoichiometry):"
echo "  * BioModels Database (curated stochastic SBML models):"
echo "      https://www.ebi.ac.uk/biomodels    (license: CC0 for curated models)"
echo "  * NIST Chemical Kinetics Database (rate constants):"
echo "      https://kinetics.nist.gov"
echo "  * DANDI (single-molecule tracking):    https://dandiarchive.org"
echo "  * GEO (smFISH single-cell counts):     https://www.ncbi.nlm.nih.gov/geo/"
echo
echo "SBML parsing is intentionally left as an exercise; respect each model's"
echo "license and never bypass any required registration."
