# ===========================================================================
# scripts/download_data.ps1  --  Fetch a FULL dataset (Windows / PowerShell)
# ---------------------------------------------------------------------------
# Project 6.11 : Stochastic (Gillespie) Biochemical Simulation
#
# CONTRACT (CLAUDE.md §8): idempotent, documented, prints the source URLs, and
# NEVER bypasses credentials/registration. This project's demo needs NO download
# -- its input is a tiny synthetic model spec generated by make_synthetic.py.
# This script only points you at real curated models for further study.
#
# Usage:  ./scripts/download_data.ps1
# ===========================================================================
$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path -Parent $PSScriptRoot
$DataDir = Join-Path $ProjectRoot "data"

Write-Host "[download_data] Project 6.11 -- Stochastic (Gillespie) Biochemical Simulation"
Write-Host "[download_data] Target data dir: $DataDir"
Write-Host ""
Write-Host "This project does NOT require a downloaded dataset:"
Write-Host "  the committed data/sample/gene_network.txt (a synthetic model spec) is"
Write-Host "  sufficient to build, run, and verify the demo offline."
Write-Host ""
Write-Host "For a larger SYNTHETIC ensemble, run:"
Write-Host "    python scripts/make_synthetic.py --n-traj 4096"
Write-Host ""
Write-Host "To study REAL stochastic reaction networks (adapt build_gene_network()"
Write-Host "in src/reference_cpu.cpp to their stoichiometry):"
Write-Host "  * BioModels Database (curated stochastic SBML models):"
Write-Host "      https://www.ebi.ac.uk/biomodels    (license: CC0 for curated models)"
Write-Host "  * NIST Chemical Kinetics Database (rate constants):"
Write-Host "      https://kinetics.nist.gov"
Write-Host "  * DANDI (single-molecule tracking):    https://dandiarchive.org"
Write-Host "  * GEO (smFISH single-cell counts):     https://www.ncbi.nlm.nih.gov/geo/"
Write-Host ""
Write-Host "SBML parsing is intentionally left as an exercise; respect each model's"
Write-Host "license and never bypass any required registration."
