# ===========================================================================
# scripts/download_data.ps1  --  Fetch the FULL dataset (Windows / PowerShell)
# ---------------------------------------------------------------------------
# Project 5.2 -- Radiotherapy Treatment-Plan Optimization   (template skeleton)
#
# CONTRACT (CLAUDE.md §8): idempotent, documented, prints the source URL +
# expected size + checksum, and NEVER bypasses credentials/registration. If a
# dataset needs an account, this script only prints instructions + links and
# defers to scripts/make_synthetic.py for an offline stand-in.
#
# Usage:  ./scripts/download_data.ps1
# ===========================================================================
$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path -Parent $PSScriptRoot
$DataDir = Join-Path $ProjectRoot "data"

Write-Host "[download_data] Project 5.2 -- Radiotherapy Treatment-Plan Optimization"
Write-Host "[download_data] Target data dir: $DataDir"

# There is no single 'download' for FMO: real inputs are dose-influence (dij)
# matrices generated by a treatment-planning system from a patient CT. This
# script prints where to get realistic data and does NOT bypass any license /
# registration (CLAUDE.md 8). The committed synthetic sample already runs the demo.
Write-Host ""
Write-Host "  This project runs offline on the SYNTHETIC sample in data/sample/."
Write-Host "  To generate a larger synthetic problem:"
Write-Host "    python scripts/make_synthetic.py --n-vox 4096 --n-beam 256"
Write-Host ""
Write-Host "  For REALISTIC dose-influence matrices and RT datasets, study:"
Write-Host "    matRad     https://github.com/e0404/matRad    (exports the dij matrix)"
Write-Host "    pyRadPlan  https://github.com/e0404/pyRadPlan  (Python port of matRad)"
Write-Host "    OpenKBP    https://github.com/ababier/open-kbp (340 H&N IMRT plans)"
Write-Host "    CERR       https://github.com/cerr/CERR        (DICOM-RT research platform)"
Write-Host "    OpenTPS    https://opentps.org/                (Python/GPU planning)"
Write-Host "    TCIA RT collections; AAPM TG-263 structure naming standard."
Write-Host ""
Write-Host "  Respect every dataset's license; several forbid redistribution, which"
Write-Host "  is why the committed sample is synthetic. See data/README.md."
