#!/usr/bin/env bash
# ===========================================================================
# scripts/download_data.sh  --  Fetch the FULL dataset (Linux / macOS)
# ---------------------------------------------------------------------------
# Project 5.2 -- Radiotherapy Treatment-Plan Optimization   (template skeleton)
#
# CONTRACT (CLAUDE.md §8): idempotent, documented, prints source URL + expected
# size + checksum, and NEVER bypasses credentials/registration. Defers to
# scripts/make_synthetic.py for an offline stand-in when needed.
#
# Usage:  ./scripts/download_data.sh
# ===========================================================================
set -euo pipefail
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DATA_DIR="$PROJECT_ROOT/data"

echo "[download_data] Project 5.2 -- Radiotherapy Treatment-Plan Optimization"
echo "[download_data] Target data dir: $DATA_DIR"
echo

# There is no single 'download' for FMO: real inputs are dose-influence (dij)
# matrices generated by a treatment-planning system from a patient CT. This
# script prints where to get realistic data and does NOT bypass any license /
# registration (CLAUDE.md 8). The committed synthetic sample already runs the demo.
echo "  This project runs offline on the SYNTHETIC sample in data/sample/."
echo "  To generate a larger synthetic problem:"
echo "    python scripts/make_synthetic.py --n-vox 4096 --n-beam 256"
echo
echo "  For REALISTIC dose-influence matrices and RT datasets, study:"
echo "    matRad     https://github.com/e0404/matRad    (exports the dij matrix)"
echo "    pyRadPlan  https://github.com/e0404/pyRadPlan  (Python port of matRad)"
echo "    OpenKBP    https://github.com/ababier/open-kbp (340 H&N IMRT plans)"
echo "    CERR       https://github.com/cerr/CERR        (DICOM-RT research platform)"
echo "    OpenTPS    https://opentps.org/                (Python/GPU planning)"
echo "    TCIA RT collections; AAPM TG-263 structure naming standard."
echo
echo "  Respect every dataset's license; several forbid redistribution, which"
echo "  is why the committed sample is synthetic. See data/README.md."
