#!/usr/bin/env python3
# ===========================================================================
# scripts/make_synthetic.py  --  Generate the synthetic radial-MRI sample dataset
# ---------------------------------------------------------------------------
# Project 4.33 : Real-Time MRI Reconstruction
#
# WHY THIS EXISTS
#   The real public datasets for this project (ACDC, CMRxRecon, fastMRI) require
#   registration / a data-use agreement and CANNOT be redistributed here (see
#   data/README.md). So the committed demo runs on a SMALL, clearly-SYNTHETIC phantom
#   generated by this script. Nothing here is patient data.
#
# WHAT IT PRODUCES  (matches load_radial() in src/reference_cpu.cpp)
#   A GOLDEN-ANGLE RADIAL acquisition of a sparse 2D phantom that MOVES slightly over
#   time (like a beating heart), so a SLIDING WINDOW of spokes produces a genuine
#   little movie. We:
#     1. define a phantom as a sum of Gaussian blobs (an "MR angiogram"-like image);
#     2. for each radial spoke (at the golden angle) and each readout sample along it,
#        evaluate the phantom's ANALYTIC 2D Fourier transform at that k-space point
#        (a Gaussian's FT is another Gaussian, so we need no FFT here) -- this is the
#        physically-correct k-space the scanner would measure;
#     3. write every complex sample "re im", spoke-major;
#     4. write the ground-truth magnitude image (the phantom sampled on the n x n
#        grid at the LAST frame's time) so the reconstructor can score itself.
#
#   The acquisition is DETERMINISTIC (no RNG): the golden angle and the analytic FT
#   are exact, so the sample -- and therefore demo/expected_output.txt -- is stable.
#
#   Pure standard-library Python (no numpy) so it runs anywhere. Sizes are tiny.
#
# USAGE
#   python scripts/make_synthetic.py                 # writes data/sample/radial_sample.txt
#   python scripts/make_synthetic.py --n 64 --spokes 96 --win 24 --frames 6
# ===========================================================================
import argparse
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent          # the project folder
OUT = ROOT / "data" / "sample" / "radial_sample.txt"

# The golden angle in radians (must match grid_core.h golden_angle_rad()).
GOLDEN_DEG = 111.2461179749811


def blobs_at_time(n, t):
    """Return the phantom's blobs at normalized time t in [0,1].

    Each blob is (dx, dy, amplitude, sigma_px) where (dx, dy) is the blob CENTER
    measured in PIXELS RELATIVE TO THE IMAGE CENTER (n/2, n/2). Center-referenced
    coordinates pair with the standard reconstruction convention -- ifftshift, ifft2,
    fftshift (see reconstruct_frame_cpu) -- so the anatomy lands centered. One blob
    gently BOBS so a sliding window over spokes acquired at different times yields a
    genuine little movie -- the whole point of real-time MRI. Sigmas are a few pixels
    so the phantom's k-space energy sits at the LOW frequencies a sparse radial
    trajectory samples well (a tiny blob would need dense high-frequency spokes we do
    not acquire). Returns a list of (dx, dy, amp, sigma_px).
    """
    # A slow vertical bob of the brightest blob (amplitude ~4% of the FOV, in pixels).
    bob = 0.04 * n * math.sin(2.0 * math.pi * t)
    return [
        # (dx from center, dy from center, amplitude, sigma in pixels)
        (-0.09 * n, -0.09 * n + bob, 1.00, 0.050 * n),   # the "moving" bright blob
        ( 0.10 * n,  0.10 * n,       0.75, 0.062 * n),
        (-0.16 * n,  0.14 * n,       0.60, 0.044 * n),
        ( 0.16 * n, -0.13 * n,       0.85, 0.041 * n),
    ]


def phantom_image(n, t):
    """Sample the phantom on the n x n image grid at time t -> flat row-major list.

    Pixel (r,c) sits at offset (c - n/2, r - n/2) from the image center; a blob with
    center-offset (dx,dy) is bright where that offset is near (dx,dy). Used ONLY to
    write the ground-truth image; the k-space samples come from the analytic FT below.
    """
    img = [0.0] * (n * n)
    cen = 0.5 * n
    for (dx, dy, amp, sig) in blobs_at_time(n, t):
        cx, cy = cen + dx, cen + dy          # absolute pixel center of the blob
        for r in range(n):
            for c in range(n):
                d2 = (c - cx) ** 2 + (r - cy) ** 2
                img[r * n + c] += amp * math.exp(-d2 / (2.0 * sig * sig))
    return img


def kspace_sample(kx, ky, n, t):
    """Analytic 2D Fourier transform of the phantom at k-space point (kx, ky).

    kx, ky are spatial frequencies in CYCLES-PER-FOV (DC = 0), about the k-space
    center. A 2D Gaussian blob amp * exp(-|x - c|^2 / (2 sigma^2)) centered at offset
    (dx,dy) from the image center has the analytic FT
        amp * (2 pi sigma^2) * exp(-2 pi^2 sigma^2 (kx^2+ky^2)/FOV^2)
              * exp(-2 pi i (kx*dx + ky*dy)/FOV)
    with FOV = n pixels and (dx,dy) the CENTER-RELATIVE offset (which pairs with the
    ifftshift/fftshift reconstruction convention). Returns (re, im) summed over all
    blobs. EXACT (no discretization) -> a clean problem to verify.
    """
    two_pi = 2.0 * math.pi
    acc_re, acc_im = 0.0, 0.0
    for (dx, dy, amp, sig) in blobs_at_time(n, t):
        # Gaussian magnitude envelope in k-space (FOV = n).
        env = amp * (two_pi * sig * sig) * math.exp(
            -2.0 * math.pi * math.pi * sig * sig * (kx * kx + ky * ky) / (n * n))
        # Linear phase from the blob's CENTER-RELATIVE offset.
        ph = -two_pi * (kx * dx + ky * dy) / n
        acc_re += env * math.cos(ph)
        acc_im += env * math.sin(ph)
    return acc_re, acc_im


def main():
    ap = argparse.ArgumentParser(description="Generate the synthetic radial-MRI sample.")
    ap.add_argument("--n", type=int, default=32, help="grid / image side (power of two)")
    ap.add_argument("--spokes", type=int, default=64, help="total golden-angle spokes")
    ap.add_argument("--ro", type=int, default=64, help="readout samples per spoke")
    ap.add_argument("--win", type=int, default=21, help="spokes per sliding-window frame")
    ap.add_argument("--stride", type=int, default=8, help="spokes advanced per frame")
    ap.add_argument("--frames", type=int, default=6, help="number of frames to reconstruct")
    ap.add_argument("--kbw", type=int, default=4, help="Kaiser-Bessel kernel width (cells)")
    ap.add_argument("--out", default=str(OUT), help="output path")
    args = ap.parse_args()

    n = args.n
    assert n > 0 and (n & (n - 1)) == 0, "n must be a power of two"
    assert args.win <= args.spokes, "win cannot exceed the number of spokes"
    # The last frame's window must fit within the acquired spokes.
    last_start = (args.frames - 1) * args.stride
    assert last_start + args.win <= args.spokes, (
        "frames*stride + win exceeds spokes; reduce --frames/--stride or add --spokes")

    # We tie the acquisition "time" of a spoke to its index so the phantom moves as
    # spokes stream in. Time of spoke s = s / (spokes-1), in [0,1]. The ground-truth
    # image is taken at the time of the LAST frame's window CENTER (what that frame
    # should look like), matching main.cu's "last-frame vs truth" check.
    def spoke_time(s):
        return s / max(1, args.spokes - 1)

    # --- Radial k-space samples (spoke-major, readout-minor) ------------------
    sample_lines = []
    for s in range(args.spokes):
        theta = math.radians(s * GOLDEN_DEG)
        ct, st = math.cos(theta), math.sin(theta)
        t = spoke_time(s)
        for j in range(args.ro):
            # Readout offset in grid cells: sample j runs the spoke across the grid
            # diameter [-n/2, n/2] (matches sample_kpos() in reference_cpu.cpp).
            ro = (j - 0.5 * args.ro) * (n / args.ro)
            kx = ro * ct    # k-space frequency (cycles per FOV) along the spoke
            ky = ro * st
            re, im = kspace_sample(kx, ky, n, t)
            sample_lines.append(f"{re:.7g} {im:.7g}")

    # --- Ground-truth image at the last frame's central time ------------------
    last_center_spoke = last_start + args.win // 2
    t_truth = spoke_time(last_center_spoke)
    truth = phantom_image(n, t_truth)

    # --- Assemble the file ----------------------------------------------------
    header = (f"{n} {args.spokes} {args.ro} {args.win} {args.stride} "
              f"{args.frames} {args.kbw} 1")           # has_truth = 1
    lines = [header]
    lines.extend(sample_lines)
    lines.extend(f"{v:.7g}" for v in truth)

    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[make_synthetic] wrote {args.out}")
    print(f"[make_synthetic] n={n}, spokes={args.spokes}x{args.ro} readout, "
          f"win={args.win}, stride={args.stride}, frames={args.frames}; SYNTHETIC")


if __name__ == "__main__":
    main()
