#!/usr/bin/env python3
# ===========================================================================
# scripts/make_synthetic.py  --  Generate the synthetic TG-43 plan sample
# ---------------------------------------------------------------------------
# Project 5.7 : Brachytherapy Dose & Source Modeling
#
# WHY THIS EXISTS
#   The real AAPM TG-43 consensus source datasets are published in journal
#   tables (see data/README.md) and are not committed here. To keep the demo
#   runnable offline we generate a small, clearly-SYNTHETIC plan that mimics the
#   SHAPE of a real one (a short Ir-192-like line source, a plausible radial
#   dose function, a mild 2-D anisotropy table, and a few collinear dwells).
#
#   The default output is byte-identical to the committed
#   data/sample/plan_sample.txt and matches src/main.cu's built-in fallback, so
#   the program produces the SAME deterministic stdout whether it reads the file
#   or uses the built-in plan. Nothing here is measured or clinical.
#
# USAGE
#   python scripts/make_synthetic.py                 # rewrite the committed sample
#   python scripts/make_synthetic.py --grid 81       # a larger (81x81) grid
#   python scripts/make_synthetic.py --dwells 7      # more dwell positions
# ===========================================================================
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent          # the project folder
OUT = ROOT / "data" / "sample" / "plan_sample.txt"

# The teaching source model (SYNTHETIC -- not an AAPM consensus dataset).
L = 0.35            # active length [cm] (Ir-192 HDR pellet scale)
LAMBDA = 1.109      # dose-rate constant [cGy/(h*U)] (Ir-192-like magnitude)

# Radial dose function g_L(r): (radius[cm], value). ~1 near 1 cm, falling with r.
G_TABLE = [
    (0.25, 0.980), (0.50, 1.010), (1.00, 1.000), (2.00, 0.965),
    (3.00, 0.910), (5.00, 0.780), (7.00, 0.650),
]

# 2-D anisotropy F(r, theta): 1 on the transverse plane (theta=90), lower at the
# poles where the source self-absorbs. Rows are radii, columns are angles.
F_RADII = [0.5, 1.0, 3.0]
F_ANGLES = [0.0, 45.0, 90.0, 135.0, 180.0]
F_VALUES = [
    [0.62, 0.90, 1.00, 0.90, 0.62],   # r = 0.5 cm
    [0.68, 0.93, 1.00, 0.93, 0.68],   # r = 1.0 cm
    [0.75, 0.95, 1.00, 0.95, 0.75],   # r = 3.0 cm
]


def build_dwells(n: int):
    """n collinear dwells evenly spaced along z at x=y=0, unit weight each.
    n=3 reproduces the committed sample exactly (z = -0.5, 0.0, +0.5)."""
    if n == 3:
        return [(0.0, 0.0, -0.5, 1.0), (0.0, 0.0, 0.0, 1.0), (0.0, 0.0, 0.5, 1.0)]
    # General case: span [-0.5, +0.5] cm inclusive.
    dwells = []
    for k in range(n):
        z = -0.5 + (1.0 * k / (n - 1)) if n > 1 else 0.0
        dwells.append((0.0, 0.0, round(z, 4), 1.0))
    return dwells


def main():
    ap = argparse.ArgumentParser(description="Generate the synthetic TG-43 plan.")
    ap.add_argument("--grid", type=int, default=41, help="grid size (grid x grid x 1)")
    ap.add_argument("--dwells", type=int, default=3, help="number of dwell positions")
    ap.add_argument("--out", default=str(OUT), help="output path")
    args = ap.parse_args()

    n = args.grid
    origin = -(n // 2) * 0.1   # center the grid on the sources (1 mm spacing)
    dwells = build_dwells(args.dwells)

    lines = []
    lines.append("# SYNTHETIC TG-43 brachytherapy plan (Project 5.7) -- not clinical.")
    lines.append("# Generated by scripts/make_synthetic.py. See data/README.md.")
    lines.append("")
    lines.append("# source: L[cm]  Lambda[cGy/(h*U)]")
    lines.append(f"{L:g}   {LAMBDA:g}")
    lines.append("")
    lines.append("# radial dose function g_L(r): count, then (r  g) per line")
    lines.append(str(len(G_TABLE)))
    for r, g in G_TABLE:
        lines.append(f"{r:g}   {g:g}")
    lines.append("")
    lines.append("# anisotropy F(r,theta): n_Fr n_Ft, radii, angles, then rows")
    lines.append(f"{len(F_RADII)}   {len(F_ANGLES)}")
    lines.append("   ".join(f"{r:g}" for r in F_RADII))
    lines.append("   ".join(f"{a:g}" for a in F_ANGLES))
    for row in F_VALUES:
        lines.append("   ".join(f"{v:g}" for v in row))
    lines.append("")
    lines.append("# dose grid: nx ny nz  ox oy oz  spacing")
    lines.append(f"{n}   {n}   1   {origin:g}   {origin:g}   0.0   0.1")
    lines.append("")
    lines.append("# dwells: count, then (x y z weight) per line")
    lines.append(str(len(dwells)))
    for (x, y, z, w) in dwells:
        lines.append(f"{x:g}   {y:g}   {z:g}   {w:g}")

    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[make_synthetic] wrote {args.out}  "
          f"(grid={n}x{n}, dwells={len(dwells)}; SYNTHETIC, not clinical)")


if __name__ == "__main__":
    main()
