# ===========================================================================
# scripts/download_data.ps1  --  Point at the FULL datasets (Windows / PowerShell)
# ---------------------------------------------------------------------------
# Project 5.11 : Microdosimetry & Track-Structure Simulation
#
# CONTRACT (CLAUDE.md §8): idempotent, documented, prints source URLs, and NEVER
# bypasses credentials/registration. This teaching project has NO single
# downloadable dataset -- its input is a handful of parameters generated by
# scripts/make_synthetic.py -- so this script prints pointers to the real-world
# resources you would consult when extending it toward a research code.
#
# Usage:  ./scripts/download_data.ps1
# ===========================================================================
$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path -Parent $PSScriptRoot
$DataDir = Join-Path $ProjectRoot "data"

Write-Host "[download_data] Project 5.11 -- Microdosimetry & Track-Structure Simulation"
Write-Host "[download_data] Target data dir: $DataDir"
Write-Host ""
Write-Host "This project uses a SYNTHETIC parameter file, not a downloaded dataset."
Write-Host "The committed data/sample/track_params.txt already runs the demo offline."
Write-Host "Regenerate or vary it with:  python scripts/make_synthetic.py --help"
Write-Host ""
Write-Host "Real-world resources (respect each license; none is redistributed here):"
Write-Host "  * Geant4-DNA physics validation data  https://geant4-dna.in2p3.fr/"
Write-Host "      liquid-water interaction cross-sections (replaces scalar sigma_ion)"
Write-Host "  * NIST ESTAR electron stopping powers  https://www.nist.gov/pml/estar"
Write-Host "      energy -> LET conversion reference"
Write-Host "  * AAPM / NCRP microdosimetry benchmarks -- reference y-spectra f(y)"
Write-Host "  * Published DNA damage-yield datasets (SSB/DSB per Gy vs. LET) from"
Write-Host "      radiobiology experiments, to calibrate/validate the damage model"
Write-Host ""
Write-Host "When wiring a real dataset, follow this idempotent pattern:"
Write-Host "  1) skip download if the file already exists with the right checksum"
Write-Host "  2) print source URL + expected size + SHA256"
Write-Host "  3) for credentialed sets, print registration instructions ONLY"
