#!/usr/bin/env bash
# ===========================================================================
# scripts/download_data.sh  --  Point at the FULL datasets (Linux / macOS)
# ---------------------------------------------------------------------------
# Project 5.11 : Microdosimetry & Track-Structure Simulation
#
# CONTRACT (CLAUDE.md §8): idempotent, documented, prints source URLs, and NEVER
# bypasses credentials/registration. This teaching project has NO single
# downloadable dataset -- its input is a handful of parameters generated by
# scripts/make_synthetic.py -- so this script prints pointers to the real-world
# resources you would consult when extending it toward a research code.
#
# Usage:  ./scripts/download_data.sh
# ===========================================================================
set -euo pipefail
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DATA_DIR="$PROJECT_ROOT/data"

echo "[download_data] Project 5.11 -- Microdosimetry & Track-Structure Simulation"
echo "[download_data] Target data dir: $DATA_DIR"
echo
echo "This project uses a SYNTHETIC parameter file, not a downloaded dataset."
echo "The committed data/sample/track_params.txt already runs the demo offline."
echo "Regenerate or vary it with:  python scripts/make_synthetic.py --help"
echo
echo "Real-world resources (respect each license; none is redistributed here):"
echo "  * Geant4-DNA physics validation data  https://geant4-dna.in2p3.fr/"
echo "      liquid-water interaction cross-sections (replaces scalar sigma_ion)"
echo "  * NIST ESTAR electron stopping powers  https://www.nist.gov/pml/estar"
echo "      energy -> LET conversion reference"
echo "  * AAPM / NCRP microdosimetry benchmarks -- reference y-spectra f(y)"
echo "  * Published DNA damage-yield datasets (SSB/DSB per Gy vs. LET) from"
echo "      radiobiology experiments, to calibrate/validate the damage model"
echo
echo "When wiring a real dataset, follow this idempotent pattern:"
echo "  1) skip download if the file already exists with the right checksum"
echo "  2) print source URL + expected size + SHA256"
echo "  3) for credentialed sets, print registration instructions ONLY"
