#!/usr/bin/env python3
# ===========================================================================
# scripts/make_synthetic.py  --  Generate the synthetic constant-pH sample
# ---------------------------------------------------------------------------
# Project 1.22 : Constant-pH Molecular Dynamics (reduced-scope teaching model)
#
# WHY THIS EXISTS
#   Real titration benchmarks (PKAD, PHMD) describe protonation states of actual
#   protein residues, but those reference pKa values are tied to specific PDB
#   structures and curation that we cannot redistribute wholesale. So the demo
#   ships a clearly-SYNTHETIC, hand-authored toy system: a 3-residue line (an
#   acid flanked by two bases) engineered so the result is interpretable -- the
#   electrostatic coupling visibly shifts each residue's apparent pKa off its
#   intrinsic value, which is the whole point of constant-pH simulation.
#   Synthetic data is always LABELED synthetic (CLAUDE.md §8).
#
#   This generator writes the SAME file already committed at
#   data/sample/cph_system.txt; it exists so a learner can regenerate or tweak it
#   (move residues, change the dielectric, add a residue) and re-run the demo.
#
# FILE FORMAT (consumed by src/reference_cpu.cpp load_cph_problem):
#   line 1:  n_res  coulomb_k  kT      sweeps  burn_in
#   line 2:  pH_min pH_max     n_pH    replicas seed
#   then n_res lines:  pKa_intrinsic  q_prot  q_deprot   x   y   z
#
# USAGE
#   python scripts/make_synthetic.py                 # -> data/sample/cph_system.txt
#   python scripts/make_synthetic.py --coulomb_k 0   # coupling OFF (H-H check)
#   python scripts/make_synthetic.py --spacing 4     # tighter spacing, bigger shift
# ===========================================================================
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent              # the project folder
OUT = ROOT / "data" / "sample" / "cph_system.txt"

# The default 3-residue toy: (label, intrinsic_pKa, q_prot, q_deprot).
# ASP is an acid (neutral protonated, -1 deprotonated); HIS/LYS are bases
# (+1 protonated, neutral deprotonated). Positions are assigned along x by
# --spacing so the inter-residue electrostatics are easy to reason about.
RESIDUES = [
    ("ASP",  4.0, 0.0, -1.0),   # acid
    ("HIS",  6.5, 1.0,  0.0),   # base
    ("LYS", 10.5, 1.0,  0.0),   # base
]


def main():
    ap = argparse.ArgumentParser(description="Generate the synthetic constant-pH system.")
    ap.add_argument("--coulomb_k", type=float, default=12.0,
                    help="Coulomb prefactor 332.06/epsilon (set 0 to disable coupling)")
    ap.add_argument("--kT", type=float, default=0.593, help="thermal energy kcal/mol")
    ap.add_argument("--sweeps", type=int, default=6000, help="MC sweeps per chain")
    ap.add_argument("--burn_in", type=int, default=1000, help="discarded leading sweeps")
    ap.add_argument("--pH_min", type=float, default=0.0)
    ap.add_argument("--pH_max", type=float, default=14.0)
    ap.add_argument("--n_pH", type=int, default=15, help="pH grid points")
    ap.add_argument("--replicas", type=int, default=8, help="chains averaged per pH")
    ap.add_argument("--seed", type=int, default=20260628, help="base RNG seed")
    ap.add_argument("--spacing", type=float, default=7.0, help="residue spacing (A)")
    ap.add_argument("--out", default=str(OUT), help="output path")
    args = ap.parse_args()

    lines = []
    lines.append("# SYNTHETIC constant-pH system generated by scripts/make_synthetic.py")
    lines.append("# (3-residue toy: acid ASP flanked by bases HIS, LYS; NOT a real protein)")
    lines.append(f"{len(RESIDUES)}   {args.coulomb_k:g}   {args.kT:g}   "
                 f"{args.sweeps}   {args.burn_in}")
    lines.append(f"{args.pH_min:g} {args.pH_max:g}   {args.n_pH}      "
                 f"{args.replicas}      {args.seed}")
    lines.append("#  pKa   q_prot  q_deprot    x     y     z      residue")
    for i, (label, pka, qp, qd) in enumerate(RESIDUES):
        x = i * args.spacing
        lines.append(f"  {pka:4.1f}   {qp:4.1f}   {qd:5.1f}     {x:5.1f}  0.0   0.0   # {label}")

    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[make_synthetic] wrote {args.out}  "
          f"(coupling_k={args.coulomb_k}, spacing={args.spacing} A; SYNTHETIC)")


if __name__ == "__main__":
    main()
