#!/usr/bin/env python3
# ===========================================================================
# scripts/make_synthetic.py  --  Generate a synthetic featurized MD trajectory
# ---------------------------------------------------------------------------
# Project 1.17 : Markov State Models from MD
#
# WHAT THIS BUILDS
#   A single, time-ordered "trajectory" of N frames in a D-dimensional feature
#   space (a stand-in for tICA / collective-variable coordinates of an MD run).
#   The trajectory is generated by a HIDDEN K-state Markov chain: at each step
#   the system is in one of K metastable basins and hops to another basin with
#   the probabilities in GROUND_TRUTH_T. Each basin emits a feature point near
#   its center with small Gaussian jitter (the fast in-basin vibrations).
#
#   Because the basins are well separated, k-means recovers one microstate per
#   basin, and the MSM's estimated transition matrix should approximate
#   GROUND_TRUTH_T -- so the demo's result is INTERPRETABLE and verifiable
#   (PATTERNS.md section 6: engineer the sample so a known answer is recovered).
#   The chain is "sticky" (high self-transition probability), creating a clear
#   SLOW process whose implied timescale the MSM reports.
#
#   Values are normalized to [0,1] so the fixed-point centroid accumulation in
#   msm.h is valid. Real data comes from MD trajectories (see download_data.*).
#   This dataset is SYNTHETIC and carries no physical/clinical meaning.
#
# OUTPUT (data/README.md format):  header "N D K lag"  then N rows of D floats.
#
# USAGE
#   python scripts/make_synthetic.py
#   python scripts/make_synthetic.py --frames 20000   # longer trajectory
# ===========================================================================
import argparse
import random
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "data" / "sample" / "trajectory_sample.txt"

# K=3 metastable basins in a D=3 feature space. Centers are well separated in
# [0,1]^3 so clustering is unambiguous (e.g. "unfolded", "intermediate",
# "folded" conformational basins).
BASIN_CENTERS = [
    [0.20, 0.20, 0.25],   # basin 0
    [0.80, 0.30, 0.75],   # basin 1
    [0.50, 0.85, 0.40],   # basin 2
]

# GROUND-TRUTH transition matrix of the hidden chain (row = from, col = to).
# Sticky diagonal -> long dwell times -> a clear slow process. The MSM built
# from the generated trajectory should approximate this matrix.
GROUND_TRUTH_T = [
    [0.94, 0.05, 0.01],
    [0.04, 0.93, 0.03],
    [0.02, 0.04, 0.94],
]

JITTER = 0.035   # Gaussian std of the in-basin fast motion (per feature)


def clip01(v):
    return 0.0 if v < 0.0 else (1.0 if v > 1.0 else v)


def sample_next_state(rng, T_row):
    # Inverse-CDF sampling of the next basin from one row of the transition matrix.
    u = rng.random()
    acc = 0.0
    for j, p in enumerate(T_row):
        acc += p
        if u <= acc:
            return j
    return len(T_row) - 1   # numerical safety: land in the last state


def main():
    ap = argparse.ArgumentParser(description="Generate a synthetic featurized MD trajectory.")
    ap.add_argument("--frames", type=int, default=12000, help="number of MD frames N")
    ap.add_argument("--lag", type=int, default=1, help="MSM lag time tau, in frames")
    ap.add_argument("--jitter", type=float, default=JITTER, help="in-basin Gaussian std")
    ap.add_argument("--seed", type=int, default=7)
    ap.add_argument("--out", default=str(OUT))
    args = ap.parse_args()

    rng = random.Random(args.seed)
    D = len(BASIN_CENTERS[0])
    K = len(BASIN_CENTERS)

    # Walk the hidden chain, emitting one feature point per frame.
    state = 0
    rows = []
    for _ in range(args.frames):
        center = BASIN_CENTERS[state]
        frame = [clip01(center[j] + rng.gauss(0.0, args.jitter)) for j in range(D)]
        rows.append(" ".join(f"{v:.5f}" for v in frame))
        state = sample_next_state(rng, GROUND_TRUTH_T[state])

    N = len(rows)
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text(f"{N} {D} {K} {args.lag}\n" + "\n".join(rows) + "\n",
                              encoding="utf-8")
    print(f"[make_synthetic] wrote {args.out}  "
          f"(N={N} frames, D={D} features, K={K} basins, lag={args.lag}; SYNTHETIC)")


if __name__ == "__main__":
    main()
