# ===========================================================================
# scripts/download_data.ps1  --  Fetch reference data / point to sources (Windows)
# ---------------------------------------------------------------------------
# Project 6.7 : Spiking Neural Network (Point-Neuron) Simulation
#
# CONTRACT (CLAUDE.md §8): idempotent, documented, prints source URLs, and NEVER
# bypasses credentials/registration. This project does NOT need any download to
# run: the "dataset" is the synthetic network config generated by
# scripts/make_synthetic.py. The links below are for learners who want to compare
# the simulator against real recordings or wire in a real structural connectome.
#
# Usage:  ./scripts/download_data.ps1
# ===========================================================================
$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path -Parent $PSScriptRoot
$DataDir = Join-Path $ProjectRoot "data"

Write-Host "[download_data] Project 6.7 -- Spiking Neural Network (Point-Neuron) Simulation"
Write-Host "[download_data] Target data dir: $DataDir"
Write-Host ""
Write-Host "  This project runs entirely on a SYNTHETIC network config -- no download"
Write-Host "  is required. Regenerate or resize it with:"
Write-Host "    python scripts/make_synthetic.py                 # the committed sample"
Write-Host "    python scripts/make_synthetic.py --n-exc 8000 --n-inh 2000 --steps 2000"
Write-Host ""
Write-Host "  Real datasets you can validate a point-neuron model against (all require"
Write-Host "  their own registration / terms; this script does NOT bypass any of them):"
Write-Host "    * Allen Brain Observatory (Neuropixels visual-cortex spikes):"
Write-Host "        https://portal.brain-map.org"
Write-Host "    * DANDI Archive (electrophysiology, NWB format):"
Write-Host "        https://dandiarchive.org"
Write-Host "    * OpenNeuro (EEG/MEG for network-model validation):"
Write-Host "        https://openneuro.org"
Write-Host "    * Human Connectome Project (structural connectivity matrices):"
Write-Host "        https://db.humanconnectome.org"
Write-Host ""
Write-Host "  To use a real structural connectome as the wiring, replace the hash-based"
Write-Host "  synapse_target() in src/lif.h with a lookup into a loaded adjacency list"
Write-Host "  (see THEORY.md 'Where this sits in the real world')."
