#!/usr/bin/env bash
# ===========================================================================
# scripts/download_data.sh  --  Fetch reference data / point to sources (Linux/macOS)
# ---------------------------------------------------------------------------
# Project 6.7 : Spiking Neural Network (Point-Neuron) Simulation
#
# CONTRACT (CLAUDE.md §8): idempotent, documented, prints source URLs, and NEVER
# bypasses credentials/registration. This project does NOT need any download to
# run: the "dataset" is the synthetic network config generated by
# scripts/make_synthetic.py. The links below are for learners who want to compare
# the simulator against real recordings or wire in a real structural connectome.
#
# Usage:  ./scripts/download_data.sh
# ===========================================================================
set -euo pipefail
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DATA_DIR="$PROJECT_ROOT/data"

echo "[download_data] Project 6.7 -- Spiking Neural Network (Point-Neuron) Simulation"
echo "[download_data] Target data dir: $DATA_DIR"
echo
echo "  This project runs entirely on a SYNTHETIC network config -- no download"
echo "  is required. Regenerate or resize it with:"
echo "    python scripts/make_synthetic.py                 # the committed sample"
echo "    python scripts/make_synthetic.py --n-exc 8000 --n-inh 2000 --steps 2000"
echo
echo "  Real datasets you can validate a point-neuron model against (all require"
echo "  their own registration / terms; this script does NOT bypass any of them):"
echo "    * Allen Brain Observatory (Neuropixels visual-cortex spikes):"
echo "        https://portal.brain-map.org"
echo "    * DANDI Archive (electrophysiology, NWB format):"
echo "        https://dandiarchive.org"
echo "    * OpenNeuro (EEG/MEG for network-model validation):"
echo "        https://openneuro.org"
echo "    * Human Connectome Project (structural connectivity matrices):"
echo "        https://db.humanconnectome.org"
echo
echo "  To use a real structural connectome as the wiring, replace the hash-based"
echo "  synapse_target() in src/lif.h with a lookup into a loaded adjacency list"
echo "  (see THEORY.md 'Where this sits in the real world')."
